name: Generate GitHub cards

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 */12 * * *"

jobs:
  build-and-generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"       # remove: cache: pnpm

      - name: Enable corepack (pnpm)
        run: corepack enable

      - name: Use pnpm 9
        run: corepack prepare pnpm@9 --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build and generate cards
        env:
          GITHUB_TOKEN: ${{ secrets.GH_CARDS_PAT }}
        run: pnpm generate:all

      - name: Commit updated cards
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update overview cards"
          file_pattern: "cards/*.svg"
        env:
          GIT_AUTHOR_NAME: NawfalRAZOUK7
          GIT_AUTHOR_EMAIL: 58399251+NawfalRAZOUK7@users.noreply.github.com
          GIT_COMMITTER_NAME: NawfalRAZOUK7
          GIT_COMMITTER_EMAIL: 58399251+NawfalRAZOUK7@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GH_CARDS_PAT }}
